### ISSUE TITLE
To-do for next PR (Draft)

### ISSUE THREAD

**Issue by msakr21** [Consultancy-2208/west_fl_wx_fe#11]
This is just a placeholder issue to be filled per our discussion on what we'd like to accomplish for our next PR.

Features:
- [x] OAuth implementation for registration
~- [ ] Session New Page~
- [x] OAuth implementation for login ~(session new page)!

Fixes:
- [x] New Form Page pets hidden field and checkbox order
- [x] Change db migration table and references to match agreed upon changes by JH
- [x] Change the flow of the registration to: oauth --> update/edit --> redirect to dashboard.

**Comment by msakr21** [comment]
The session new page is no longer needed because of OAuth implementation.

**Comment by msakr21** [comment]
This has been completed. 

Will need to add model tests for some wrapper methods I set up to be able to test the edit page.
