### ISSUE TITLE
Checklist for PR#1

### ISSUE THREAD

**Issue by msakr21** [Consultancy-2208/west_fl_wx_fe#8]
Tasks:
- [x]  Finish Root Page
- [x]  Finish User Creation Form
- [x]  Set up Schema

**Comment by msakr21** [comment]
These tasks have been completed. Will close this issue.
